from setuptools import setup, find_packages

setup(
    name="multimodal-fsl-pain",
    version="1.0.0",
    description="Self-Supervised Contrastive Transfer Learning for Few-Shot Multimodal Infant Pain Recognition",
    author="Oussama El Othmani, Riadh Ouersighni, Sami Naouali",
    author_email="oussama.elothmani@ept.u-carthage.tn",
    url="https://github.com/oussama123-ai/multimodal-fsl-pain",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.9",
    install_requires=[
        "torch>=2.0.1",
        "torchvision>=0.15.2",
        "torchaudio>=2.0.2",
        "numpy>=1.24.0",
        "scipy>=1.10.0",
        "scikit-learn>=1.2.0",
        "pandas>=1.5.0",
        "opencv-python>=4.7.0",
        "Pillow>=9.4.0",
        "librosa>=0.10.0",
        "facenet-pytorch>=2.5.3",
        "timm>=0.9.0",
        "einops>=0.6.1",
        "matplotlib>=3.7.0",
        "seaborn>=0.12.0",
        "tqdm>=4.65.0",
        "wandb>=0.15.0",
        "hydra-core>=1.3.0",
        "omegaconf>=2.3.0",
        "PyYAML>=6.0",
        "tensorboard>=2.12.0",
        "h5py>=3.8.0",
    ],
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Topic :: Scientific/Engineering :: Medical Science Apps.",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
)
